### ISSUE TITLE
Unexpected difference in behavior of `grad` for different modes?

### ISSUE THREAD

**Issue by mstksg** [ekmett/ad#54] opened 2016-04-27 01:17 UTC
Testing out gradient of the simple function `x**y` along the x axis at y /= 0, I get different answers depending on the mode:

```
> import qualified Numeric.AD.Mode.Sparse as S
> S.grad (\[x,y] -> x**y) [0,2]
[NaN, NaN]
> import qualified Numeric.AD.Mode.Reverse as R
> R.grad (\[x,y] -> x**y) [0,2]
[NaN, NaN]
> import qualified Numeric.AD.Mode.Kahn as K
> K.grad (\[x,y] -> x**y) [0,2]
[NaN, 0.0]
```

Only the forward mode yields the mathematically "correct" answer:

```
> import qualified Numeric.AD.Mode.Forward as F
> F.grad (\[x,y] -> x**y) [0,2]
[0.0, NaN]
```

Which of the three answers is the expected behavior?  And, are all three supposed to give different answers for something like this?

**Comment by barak** [comment] 2016-04-27 13:50
The root cause is that ```0``` is not truly a zero for IEEE floating point.
````
> F.jacobian (\[x,y]->[x**y]) [0,2] !! 0
[0.0,NaN]
> sum $ zipWith (*) (F.jacobian (\[x,y]->[x**y]) [0,2] !! 0) [1,0]
NaN
````
This is a numerics issue outside the scope of the ```ad``` package per-se.

**Comment by mstksg** [comment] 2016-04-27 17:18
hm, yes, it does seem to have to do with numerics issues...

~~~
> S.grad (\[x,y] -> x**y) [x,y]
[y * x**y * recip x * 1,x**y * log x * 1]
> R.grad (\[x,y] -> x**y) [x,y]
[0 + (0 + y * x**y / x * 1),0 + (0 + x**y * log x * 1)]
> K.grad (\[x,y] -> x**y) [x,y]
[0 + (0 + y * x**y / x * 1),0 + (0 + x**y * x * 1)]
> F.grad (\[x,y] -> x**y) [x,y]
[y * x**(y - 1) * 1,1 * (x**y * log x)]
~~~

It looks like the forward-mode computes `x**(y-1)` for the first partial where the other modes compute `x**y/x` or `x**y * recip x`, which both return `NaN`.  I wonder if there is any way the non-forward mode can be tricked into using `x**(y-1)` instead of their current methods.

However, I do notice that `K.grad` actually gives a flat-out wrong answer for the second partial.. all of the other three give the correct expression `x**y * log x` more or less, but `K.grad`/Kahn mode gives `x**y * x`.  I believe this is a genuine actual bug in *ad* unrelated to numerics issues:

~~~
> S.grad (\[x,y] -> x**y) [1,1]
[1.0,0.0]
> R.grad (\[x,y] -> x**y) [1,1]
[1.0,0.0]
> F.grad (\[x,y] -> x**y) [1,1]
[1.0,0.0]
> K.grad (\[x,y] -> x**y) [1,1]
[1.0,1.0]
~~~

**Comment by ekmett** [comment] 2016-04-27 22:22
I'm guessing this kicked in when we incorporated some herbie-inspired tricks to improve numerical accuracy. IIRC, the accuracy gets much closer to the true answer almost everywhere, but it looks like it causes an issue here.

**Comment by ekmett** [comment] 2016-04-27 22:23
I don't remember if it optimized (**) though, so I might be wrong.

**Comment by ekmett** [comment] 2016-04-27 22:25
Forward explicitly hooks `(<**>)` with:

```haskell
(<**>) :: Floating a => Forward a -> Forward a -> Forward a
Zero <**> y      = auto (0 ** primal y)
_    <**> Zero   = auto 1
x    <**> Lift y = lift1 (**y) (\z -> y *^ z ** Id (y - 1)) x
x    <**> y      = lift2_ (**) (\z xi yi -> (yi * z / xi, z * log xi)) x y
```

**Comment by ekmett** [comment] 2016-04-27 22:28
and that looks like a missing log in the last Kahn case.

**Comment by ekmett** [comment] 2016-04-27 22:35
@barak In the xmacro for building the different AD modes we do:

```
instance BODY1(Num a) => Num (HEAD) where
  fromInteger 0  = zero
  fromInteger n = auto (fromInteger n)
```

this causes us to treat `0` literals specially, so we can track them for annoying corner cases like this opportunistically where possible without losing the ability to do things like treat function spaces as numeric types, but it means `auto 0` and `fromInteger 0` have subtly different semantics, the latter is what you get with a literal `0` in your code.

**Comment by mstksg** [comment] 2016-04-28 04:46
I guess, for the original question, the optimizations (?) that case the original `[0,2]` first-component gradient to be `NaN` instead of `0` is staying as-is?  Is this too much of a corner case to worry about?

**Comment by ekmett** [comment] 2017-10-18 15:11
Fixed by #64

**Closed by ekmett** 2017-10-18 15:11 UTC

**Comment by barak** [comment] 2017-10-18 18:40
In the above discourse, there are three implementations of (**), for forward, reverse, and Kahn modes.
I'd suggest that these could be unified, by having a single bit of code that gives the Jacobian of (**) in terms of its inputs, and then this Jacobian would be used differently in the various modes. With appropriate tricks I think this could be equally efficient. And if the entries of that Jacobian are not regular nums (of whatever type) but Maybe nums, with Nothing corresponding to zero, then care could be taken to not propagate NaNs through such zeros. With appropriate inlining, I don't think there would be any efficiency hit. This would shorten the code, guarantee that the various modes are kept in sync, be more modular, and make it easier to deal with these tricky NaN propagation issues.

**Comment by ekmett** [comment] 2017-10-18 21:34
I would worry about the performance / memory thrashing of the Maybe a cases for Jacobian calculation as my guess is that it really won't online very often.

That said, if we can get numbers and an implementation that shows it works, I'm all for reuse and consistency.

**Comment by ekmett** [comment] 2017-10-18 21:37
On the other hand, there is one hell of an argument to be made that it doesn't matter how little memory you use and how fast you are if you consistently return wrong answers!

**Comment by mstksg** [comment] 2017-10-20 18:49
I mean, if you're using Float, it kind of tells you where you've already decided to land on that debate ;)
